### PR TITLE
Rewrite to ensure alignment to 32 byte pages, increase performance on ESP devices.

### PR DESCRIPTION
**Pull request by mrcodetastic**
Update to examples and cleanup of eeprom_write such that it can handle any size of data and done so aligned to the 32 byte page structure of the EEPROM.

### CODE REVIEW

**Comment by Naguissa** [comment]
Hello,

I'm improving some things here and adding ATTiny support; I think you will love new tweaks ^_^


Cheers!

**Comment by Naguissa** [comment]
Hello again!

I've just released 1.2.0 revision.

You can see I've added your enhancements, but a little bit reworked to take in consideration buffer sizes and page sizes.

It's already released and should be on Arduino IDE within a hour or two.


Thanks for your work!


Cheers!
Naguissa.

**Comment by mrcodetastic** [comment]
Not a problem. Glad the changes were of use. Out of curoisty, how do you get a library published into the Arduino IDE for everyone?

**Comment by Naguissa** [comment]
Following Arduino libraries FAQ: https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

Open an issue to add one library.I.e.: https://github.com/arduino/Arduino/issues/5735

**Comment by mrcodetastic** [comment]
Excellent. Thank you!

**Pull request merged**
